"""
Source Code AI Detection Module
Detects code generated by ChatGPT, GitHub Copilot, Claude, Cursor, CodeLlama, etc.
Analyzes:
  1. Comment style & density (AI inserts excessive boilerplate, self-narrating comments)
  2. Naming convention uniformity & predictability
  3. Syntactic symmetry & standard library textbook patterns
  4. Missing project-specific idiosyncrasies (todo tags, debug statements, pragmatic shortcuts)
"""

import math
import re
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class CodeSignal:
    name: str
    ai_score: float
    weight: float
    label: str


@dataclass
class CodeResult:
    final_score: float
    verdict: str
    filename: str
    loc: int
    signals: list = field(default_factory=list)
    error: Optional[str] = None


_AI_COMMENT_PATTERNS = [
    r"//\s*(?:initialize|declare|define|import|set up|helper function)",
    r"#\s*(?:initialize|declare|define|import|set up|helper function)",
    r"/\*\*\s*\n\s*\*\s*(?:this function|method to|helper to)",
    r"#\s*Step\s*\d+:",
    r"//\s*Step\s*\d+:",
    r"#\s*Example usage:",
    r"//\s*Example usage:",
    r"#\s*Return the result",
    r"//\s*Return the result",
    r"#\s*Ensure that the input is valid",
    r"//\s*Ensure that the input is valid",
]


def analyze_comment_density_and_style(code: str) -> dict:
    lines = [l.strip() for l in code.split("\n") if l.strip()]
    if not lines:
        return {"ai_score": 0.5, "label": "Empty code file"}

    comment_lines = 0
    boilerplate_matches = 0

    for l in lines:
        if l.startswith(("#", "//", "/*", "*")):
            comment_lines += 1
            for pat in _AI_COMMENT_PATTERNS:
                if re.search(pat, l, re.IGNORECASE):
                    boilerplate_matches += 1

    ratio = comment_lines / len(lines)

    if boilerplate_matches >= 3:
        score = 0.92
        label = f"Self-narrating tutorial comment patterns ({boilerplate_matches} textbook AI markers)"
    elif ratio > 0.35 and boilerplate_matches >= 1:
        score = 0.75
        label = f"Unusually high comment ratio ({ratio:.1%}) with formal step-by-step annotation"
    elif ratio < 0.15:
        score = 0.25
        label = f"Pragmatic engineering comment ratio ({ratio:.1%})"
    else:
        score = 0.45
        label = f"Balanced comment distribution ({ratio:.1%})"

    return {"ai_score": score, "label": label, "boilerplate_hits": boilerplate_matches}


def analyze_code_structure_and_symmetry(code: str) -> dict:
    """
    AI code tends to adhere strictly to textbook formatting, with uniform function lengths
    and standard naming patterns (e.g. `data`, `result`, `item`, `process_data`).
    """
    lines = [l for l in code.split("\n") if l.strip()]
    if len(lines) < 8:
        return {"ai_score": 0.5, "label": "Snippet too short for structural analysis"}

    # Human code often contains TODOs, FIXMEs, console logs, commented-out debug code
    human_markers = len(re.findall(r"\b(TODO|FIXME|HACK|XXX|temp|test1|asdf|console\.log|print\(f?['\"]here)\b", code, re.I))

    # AI canonical textbook variable naming
    ai_generic_vars = len(re.findall(r"\b(processed_data|result_list|temp_val|output_data|final_result|formatted_output)\b", code))

    if human_markers >= 2:
        score = 0.15
        label = f"Human developer artifacts detected ({human_markers} pragmatism/debug markers)"
    elif ai_generic_vars >= 2:
        score = 0.82
        label = f"Textbook generic variable patterns ({ai_generic_vars} standard synthetic names)"
    else:
        score = 0.50
        label = "Standard idiomatic code structure"

    return {"ai_score": score, "label": label}


def analyze_cyclomatic_regularity(code: str) -> dict:
    # Measure indent distribution
    indents = []
    for l in code.split("\n"):
        if l.strip():
            leading = len(l) - len(l.lstrip())
            indents.append(leading)

    if len(indents) < 5:
        return {"ai_score": 0.5, "label": "Brief code block"}

    indent_std = float(np.std(indents))
    # AI code is structurally symmetrical (indent_std 2.0-5.0)
    if indent_std < 3.5:
        score = 0.70
        label = f"High structural indentation symmetry (std={indent_std:.1f})"
    else:
        score = 0.35
        label = f"Dynamic nested nesting complexity (std={indent_std:.1f})"

    return {"ai_score": score, "label": label}


def analyze_code(code: str, filename: str = "code.py") -> CodeResult:
    lines = [l for l in code.split("\n") if l.strip()]
    loc = len(lines)

    if loc < 5:
        return CodeResult(
            final_score=0.5,
            verdict="Uncertain",
            filename=filename,
            loc=loc,
            error="Code snippet too small (minimum 5 lines required for pattern detection)."
        )

    signals: list[CodeSignal] = []

    comments = analyze_comment_density_and_style(code)
    signals.append(CodeSignal(
        name="Commentary & Boilerplate Style",
        ai_score=round(comments["ai_score"], 4),
        weight=3.5,
        label=comments["label"]
    ))

    struct_res = analyze_code_structure_and_symmetry(code)
    signals.append(CodeSignal(
        name="Developer Idiosyncrasies & Pragmatism",
        ai_score=round(struct_res["ai_score"], 4),
        weight=2.5,
        label=struct_res["label"]
    ))

    reg = analyze_cyclomatic_regularity(code)
    signals.append(CodeSignal(
        name="Syntactic Block Regularity",
        ai_score=round(reg["ai_score"], 4),
        weight=1.5,
        label=reg["label"]
    ))

    total_w = sum(s.weight for s in signals)
    final_score = sum(s.ai_score * s.weight for s in signals) / total_w if total_w > 0 else 0.5

    verdict = (
        "AI-Generated Code" if final_score >= 0.62
        else "Uncertain / Mixed" if final_score >= 0.38
        else "Likely Human Written Code"
    )

    return CodeResult(
        final_score=round(final_score, 4),
        verdict=verdict,
        filename=filename,
        loc=loc,
        signals=signals,
    )
